name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Update and install git
      run: |
        VER="$(cat bliss-version)"

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ DOCKERHUB_USERNAME }}
        password: ${{ DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: patsaindon/bliss-docker:"$VER"