name: Docker Build

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update and install git
      run: |
        apt-get update
        apt install git
        VER="$(curl -Ls http://www.blisshq.com/app/latest-linux-version | awk -F'[-.]' '{print $5}')"
        if [ "$(cat bliss-version)" != "$VER" ] ; then
          echo "$VER" > bliss-version
          git config --global user.email "$CI_EMAIL"
          git config --global user.name 'CI/CD auto-bump'
          git add bliss-version
          git commit -m "Bump bliss version"
          git remote rm origin && git remote add origin https://"$CI_USERNAME":"$CI_PASSWORD"@github.com/$CI_PROJECT_PATH.git
          git push origin HEAD:$CI_COMMIT_REF_NAME
        else
          echo "Version is unchanged ("$VER")"
        fi