name: Docker Build

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  push:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_AUTHOR: "pat.saindon@gmail.com"
      CI_USER.NAME: "utower-admin"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update and install git
      run: |
        apt-get update
        apt install git
        VER="$(curl -Ls http://www.blisshq.com/app/latest-linux-version | awk -F'[-.]' '{print $5}')"
        echo "$VER"
        if [ "$(cat bliss-version)" != "$VER" ] ; then
          echo "$VER" > bliss-version
          git config --global user.name "${{ USER_NAME }}"
          git config --global user.email "${{ USER_EMAIL }}"
          git add bliss-version
          git commit -m "Bump bliss version to $VER"
          git push
        else
          echo "Version is unchanged ("$VER")"
        fi
