name: Docker Build

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  push:
    branches: [ main ]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest bliss version
      run: |
        echo "Current version: $(cat bliss-version)"
        echo "$(curl -Ls http://www.blisshq.com/app/latest-linux-version | awk -F'[-.]' '{print $5}')"
        echo VER="$(curl -Ls http://www.blisshq.com/app/latest-linux-version | awk -F'[-.]' '{print $5}')"
        echo if [ "$(cat bliss-version)" != "$VER" ] ; then
        echo     git config --global init.defaultBranch main
        echo     git config --global user.name "${{ USER_NAME }}"
        echo     git config --global user.email "${{ USER_EMAIL }}"
        echo     git add bliss-version
        echo     git commit -m "Bump bliss version to $VER"
        echo     git push
        echo else
        echo "Version is unchanged ("$VER")"
        echo fi
      shell: bash