name: Docker Build

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  push:
    branches: [ main ]
  pull_request:

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest bliss version
      run: |
        ls -l
        check-version.sh
      shell: bash