name: Docker Build

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  push:
    branches: [ main ]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest bliss version
      run: |
        echo "Current version: $(cat bliss-version)"
        echo "$(curl -Ls http://www.blisshq.com/app/latest-linux-version | awk -F'[-.]' '{print $5}')"
        VER="$(curl -Ls http://www.blisshq.com/app/latest-linux-version | awk -F'[-.]' '{print $5}')"
        echo "Latest available version: $VER"
        if [[ "$(cat bliss-version)" != *${VER}* ]]; then
        echo "Version is changed"
        echo $VER > bliss-version
        else
        echo "Version is unchanged ("$VER")"
        fi
      shell: bash