name: Docker Build

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  push:
    branches: [ main ]
  pull_request:

jobs:
  check_version:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_ORG: gitea
      DOCKER_LATEST: nightly
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show file
      run: cat GITEA_WORK_DIR/bliss-version
      shell: bash

    - name: Get latest bliss version
      run: |
        bash GITEA_WORK_DIR/check_version.sh
